Add mutex to sources map
google/hashr pull request #25
Opened 2022-11-19 01:22 UTC by ZetaTwo

Looking at the logs in https://github.com/google/hashr/issues/21 it seems that the problematic access is hashr.go:324. This PR adds a mutex to that access. I don't know if this really is the best way to solve this but with this patch I am no longer seeing the crash.

2022-11-21 14:40 UTC, meeehow commented
I think there are two ways to solve this issue: 

1. What you proposed, however in this case we should wrap every assignment to h.processingSources map with h.processingSourcesMutex.Lock()/h.processingSourcesMutex.Unlock()
2. Use sync.Map instead of regular map to store the data 

I think 2. might be a cleaner approach here

2022-11-21 14:40 UTC, meeehow requested changes

2022-11-21 14:40 UTC, meeehow commented on core/hashr/hashr.go
> +	processingSourcesMutex sync.RWMutex
PTAL at my comment in PR

2022-11-21 14:46 UTC, ZetaTwo commented
That line is the only place where we create new entries in the map. All other places just assign to properties of an entry in the map. Would a sync.Map make any difference in that case?

2022-11-24 13:03 UTC, meeehow commented
From a low level perspective there should be no difference between creating new entry and modifying existing one, in both cases we are writing to a map. In Go concurrent writes or writes/reads are not thread safe, only concurrent reading is thread safe.

 Having sync.Map is one way of making the whole process thread safe.

2022-11-24 16:52 UTC, ZetaTwo commented
Isn't there a difference between writing to the Map structure itself, i.e. creating or deleting records and modifying the data of those records?

Regardless, sync.Map is probably the right way to go judging from this paragraph from the documentation:
> The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but
> read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for  disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.

I can update the PR to use that instead.

2022-11-24 17:23 UTC, ZetaTwo commented
Actually, nvm. Dropping the type safety seems like a terrible idea. I instead went ahead and added proper read locks to the rest of the code.

To clarify my point above:
```
map[key] = entry
```
will be a write to the map but
```
map[key].property = value
```
is just a read in the map but then modifying the contents of the entry.

2022-11-25 14:28 UTC, meeehow commented
Thanks for fixing this!

2022-11-25 14:28 UTC, merged