Add zip importer
google/hashr pull request #28
Opened 2022-11-24 23:22 UTC by ZetaTwo

Adds a zip importer. It is very similar to the targz importer but it adds an optional option to treat files with other extensions as zip files. This is useful if importing for example Java .jar files or Python .whl/.egg files which are just zip files under the hood.

2022-11-25 14:35 UTC, meeehow requested changes
Looks good, three small nits

2022-11-25 14:35 UTC, meeehow commented on README.md
> +#### Zip (and )
You might have forgotten something here :)

2022-11-25 14:35 UTC, meeehow commented on importers/zip/zip.go
> +
Maybe delete the extra space here

2022-11-25 14:35 UTC, meeehow commented on importers/zip/zip_test.go
> +	remotePath := "/x20/glinux-repo/20200108.00.00-ubuntu-desktop.zip"
Please change the gLinux/x20 paths

2022-11-26 01:47 UTC, ZetaTwo commented
Thanks for the review. Fixed.

2022-11-29 16:10 UTC, merged