Address various linting issues
google/hashr pull request #29
Opened 2022-11-26 02:19 UTC by ZetaTwo

* Remove error return type from processingWorker as it is always nil and never checked.
* Use variable read from locked dict
* grpc.WithInsecure is deprecated: use WithTransportCredentials and insecure.NewCredentials()
* Check return value of io.Copy
* Rename importer template to stop treating it as Go code that's used
* Check return value of extractWimFolder()
* Use bytes.Equal(...) instead of bytes.Compare(...) == 0

2022-11-29 16:42 UTC, ZetaTwo commented on importers/windows/windows.go
> +			err = extractWimFolder(file, filepath.Join(path, file.Name), extractionDir)
Sounds good. Although if that happens to be the case, the log message I added below could still make sense in one form or another. The question then would be whether to keep the continue statement or not. It doesn't terminate the whole function regardless.

2022-11-30 21:42 UTC, meeehow commented on importers/windows/windows.go
> +			err = extractWimFolder(file, filepath.Join(path, file.Name), extractionDir)
Yes, it does make sense, sorry for some reason I thought you are returning the error here not logging. I think in this case we can skip the "continue" keyword, can you also make this one line? 

if err := extractWimFolder(file, filepath.Join(path, file.Name), extractionDir); err != nil {
    glog.Errorf("Failed to extract Wim folder %s: %v", file.Name, err)
}

2022-11-30 21:43 UTC, meeehow requested changes
This looks good, just one small request, take a look at my last comment

2022-11-30 21:51 UTC, ZetaTwo commented on importers/windows/windows.go
> +			err = extractWimFolder(file, filepath.Join(path, file.Name), extractionDir)
Done, also since we are not aborting. I changed it from error to warning.

2022-11-30 22:13 UTC, meeehow approved these changes

2022-11-30 22:13 UTC, merged