Add importer for ISO 9660 files
google/hashr pull request #35
Opened 2023-04-02 13:55 UTC by ZetaTwo

This importer adds support for "regular" iso disk files. One issue is that it uses a fairly old package: https://pkg.go.dev/github.com/hooklift/iso9660 If this is an issue it's possible to change it to shell out to `mount` etc like the Windows importer does.

2023-04-04 08:03 UTC, meeehow requested changes
Couple of comments, mostly on naming

2023-04-04 08:03 UTC, meeehow commented on importers/iso9660/iso9660.go
> +// ID returns non-unique zip Archive ID.
Please change to ISO

2023-04-04 08:03 UTC, meeehow commented on importers/iso9660/iso9660.go
> +// LocalPath returns local path to a zip Archive .tar.gz file.
Please change that, same below

2023-04-04 08:03 UTC, meeehow commented on importers/iso9660/iso9660.go
> +// NewRepo returns new instance of zip repository.
ISO repository

2023-06-04 11:43 UTC, ZetaTwo commented
Think it should be all updated now.

2023-07-27 08:32 UTC, merged